version: "3"  
services:
version: '2.0'

services:
    redis:
        image: "redis:latest"
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - ".docker/redis:/data"
    web:
        image: nginx
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "8080:80"
        environment:
            - NGINX_PORT=80
    ws1:
        image: "node:14"
        restart: always
        working_dir: /usr/src/app
        command: sh -c "node ./app.js"
        volumes:
            - .:/usr/src/app
        environment:
            - APPID=80
    ws2:
        image: "node:14"
        restart: always
        working_dir: /usr/src/app
        command: sh -c "node ./app.js"
        volumes:
            - .:/usr/src/app
        environment:
            - APPID=80
    ws3:
        image: "node:14"
        restart: always
        working_dir: /usr/src/app
        command: sh -c "node ./app.js"
        volumes:
            - .:/usr/src/app
        environment:
            - APPID=80


